Q8. Write a search Numpy program to create a 3x4 array and iterate over it.

In [1]:
import numpy as np  

In [2]:
ar = np.arange(10,22).reshape((3, 4))

In [6]:
print("Original array:",ar,sep="\n")

Original array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [7]:
print("Each element of the array is:")
for x in np.nditer(ar):
    print(x,end=" ")

Each element of the array is:
10 11 12 13 14 15 16 17 18 19 20 21 